### PR TITLE
Fixed django warnings

### PR DESCRIPTION
**Pull request by sibuser**
Not sure about 'get_queryset' since I couldn't find any requirements what django version you support.

### CODE REVIEW

**Comment by chrisspen** [comment]
See tox.ini. I support Django 1.5 and above. It looks like get_queryset() was [added in 1.6](https://docs.djangoproject.com/en/1.9/releases/1.6/#get-query-set-and-similar-methods-renamed-to-get-queryset), so that code needs to stay.

If you update your patch to set queryset() as shown in the docs, I'll merge this.

**Comment by sibuser** [comment]
Hi, will fix it soon.

**Comment by chrisspen** [comment]
Sorry, didn't mean to close it if you're still working on it.

**Comment by sibuser** [comment]
No problem. Just got busy by some activities in my life.  You project is amazing.

**Pull request closed without merging**
