### PR TITLE
Fix #150 - FK remote field on Django>=2.0

### LINKED ISSUE #150: Django 2.1: Exception Value: 'ForeignKey' object has no attribute 'rel'
Hi all. On a clean installation in Django 2.1, when going to `/admin/chroniker/job/add/`, I get this error:

```
Environment:


Request Method: GET
Request URL: http://localhost:9000/admin/chroniker/job/add/

Django Version: 2.1.7
Python Version: 3.6.7
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.gis',
 'django.contrib.sites',
 'corsheaders',
 'chroniker',
 'rest_framework',
 'rest_framework.authtoken',
 'django_filters',
 'rest_framework_gis',
 'google_adwords.apps.GoogleAdwordsConfig',
 'one_app.apps.OneAppConfig',
 'one_app_api_v1.apps.OneAppApiV1Config',
 'one_app_importer.apps.OneAppImporterConfig',
 'one_app_pdf.apps.OneAppPDFConfig']
Installed Middleware:
['corsheaders.middleware.CorsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'applicationinsights.django.ApplicationInsightsMiddleware']



Traceback:

File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py" in _get_response
  126.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py" in _get_response
  124.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/options.py" in wrapper
  604.                 return self.admin_site.admin_view(view)(*args, **kwargs)

File "/usr/local/lib/python3.6/dist-packages/django/utils/decorators.py" in _wrapped_view
  142.                     response = view_func(request, *args, **kwargs)

File "/usr/local/lib/python3.6/dist-packages/django/views/decorators/cache.py" in _wrapped_view_func
  44.         response = view_func(request, *args, **kwargs)

File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/sites.py" in inner
  223.             return view(request, *args, **kwargs)

File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/options.py" in add_view
  1637.         return self.changeform_view(request, None, form_url, extra_context)

File "/usr/local/lib/python3.6/dist-packages/django/utils/decorators.py" in _wrapper
  45.         return bound_method(*args, **kwargs)

File "/usr/local/lib/python3.6/dist-packages/django/utils/decorators.py" in _wrapped_view
  142.                     response = view_func(request, *args, **kwargs)

File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/options.py" in changeform_view
  1525.             return self._changeform_view(request, object_id, form_url, extra_context)

File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/options.py" in _changeform_view
  1579.                 formsets, inline_instances = self._create_formsets(request, form.instance, change=False)

File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/options.py" in _create_formsets
  1935.         for FormSet, inline in self.get_formsets_with_inlines(*get_formsets_args):

File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/options.py" in get_formsets_with_inlines
  792.             yield inline.get_formset(request, obj), inline

File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/options.py" in get_formset
  2039.             fields = flatten_fieldsets(self.get_fieldsets(request, obj))

File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/options.py" in get_fieldsets
  328.         return [(None, {'fields': self.get_fields(request, obj)})]

File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/options.py" in get_fields
  319.         form = self._get_form_for_get_fields(request, obj)

File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/options.py" in _get_form_for_get_fields
  2122.         return self.get_formset(request, obj, fields=None).form

File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/options.py" in get_formset
  2119.         return inlineformset_factory(self.parent_model, self.model, **defaults)

File "/usr/local/lib/python3.6/dist-packages/django/forms/models.py" in inlineformset_factory
  1079.     FormSet = modelformset_factory(model, **kwargs)

File "/usr/local/lib/python3.6/dist-packages/django/forms/models.py" in modelformset_factory
  871.                              error_messages=error_messages, field_classes=field_classes)

File "/usr/local/lib/python3.6/dist-packages/django/forms/models.py" in modelform_factory
  551.     return type(form)(class_name, (form,), form_class_attrs)

File "/usr/local/lib/python3.6/dist-packages/django/forms/models.py" in __new__
  256.                 apply_limit_choices_to=False,

File "/usr/local/lib/python3.6/dist-packages/django/forms/models.py" in fields_for_model
  176.             formfield = formfield_callback(f, **kwargs)

File "/usr/local/lib/python3.6/dist-packages/chroniker/widgets.py" in formfield_for_dbfield
  137.             typ = db_field.rel.__class__.__name__

Exception Type: AttributeError at /admin/chroniker/job/add/
Exception Value: 'ForeignKey' object has no attribute 'rel'
```

Thank you.

### PR DESCRIPTION
**Pull request by Menda**
References:
* https://docs.djangoproject.com/en/2.0/releases/1.9/#field-rel-changes
* https://github.com/django/django/blob/1.11.15/django/db/models/fields/reverse_related.py#L60

### CODE REVIEW

**Comment by Menda** [comment]
@chrisspen Can you review it, please?

**Comment by chrisspen** [comment]
This is breaking tests.

**Comment by Menda** [comment]
One moment, do not merge, I want to do more testing on this.

**Comment by Menda** [comment]
@chrisspen it is finished, I added a couple of tests

**Comment by chrisspen** [comment]
Thanks.

**Pull request merged**
