### PR TITLE
unescape urls

### PR DESCRIPTION
**Pull request by mordechaiyosef**

### CODE REVIEW

**Comment by chrisspen** [comment]
Thanks for the PR. However, is this the correct usage for format_html()? According to [the docs](https://docs.djangoproject.com/en/2.2/ref/utils/#module-django.utils.html), you shouldn't need to use this with escape(), since that's what format_html() does behind the scenes.

**Comment by mordechaiyosef** [comment]
> Thanks for the PR. However, is this the correct usage for format_html()? According to [the docs](https://docs.djangoproject.com/en/2.2/ref/utils/#module-django.utils.html), you shouldn't need to use this with escape(), since that's what format_html() does behind the scenes.

I think in this case of URLs it is functionally the same. but you are right. you can also use mark_safe() directly

I am not 100% sure but, on the stderr_long_sample() and stderr_sample() functions to unescape it is recommended to use format_html()
It is a little more complicated because you want to unescape the \<br\> tags but in the case of a stderr stack trace with } you must keep this escaped so it doesnt break in the template.


https://docs.djangoproject.com/en/2.2/ref/utils/#module-django.utils.html
https://docs.djangoproject.com/en/2.2/_modules/django/utils/html/#format_html

> For the case of building up small HTML fragments, this function is to be preferred over string interpolation using % or str.format() directly, because it applies escaping to all arguments - just like the template system applies escaping by default.
> 
> So, instead of writing:
> 
> mark_safe("%s \<b\>%s\</b\> %s" % (
>     some_html,
>     escape(some_text),
>     escape(some_other_text),
> ))
> 
> You should instead use:
> 
> format_html("{} \<b\>{}\</b\> {}",
>     mark_safe(some_html),
>     some_text,
>     some_other_text,
> )
> 

I didn't add that part in this PR, was going to do it in another commit .

**Comment by mordechaiyosef** [comment]
un-escape logs and monitor views

**Comment by chrisspen** [comment]
Thanks for the contribution.

**Pull request merged**
