### PR TITLE
Create migration to reflect changes to models.py

### LINKED ISSUE #58: Missing migration
Just in case #56 doesn't get merged, I wanted to document the problem: it looks like there's a missing chroniker migration, so this is what happens when we install django-chroniker on the system for the first time.

``` console
$ ./manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: django_extensions, rest_framework, debug_toolbar, staticfiles, solo, messages
  Apply all migrations: foobar, chroniker, auth, downtime, admin, contenttypes, sites, sessions
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
$ ./manage.py makemigrations
Migrations for 'chroniker':
  0002_auto_20160520_1104.py:
    - Alter field frequency on job
    - Alter field hostname on job
    - Alter field maximum_log_entries on job
    - Alter field monitor_error_template on job
    - Alter field dependee on jobdependency
    - Alter field dependent on jobdependency
    - Alter field wait_for_completion on jobdependency
    - Alter field wait_for_next_run on jobdependency
    - Alter field wait_for_success on jobdependency
    - Alter field duration_seconds on log
$ ./manage.py migrate       
Operations to perform:
  Synchronize unmigrated apps: debug_toolbar, messages, django_extensions, solo, rest_framework, staticfiles
  Apply all migrations: downtime, chroniker, auth, sessions, admin, foobar, contenttypes, sites
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying chroniker.0002_auto_20160520_1104... OK
```

Instead of having just being able to use the migrations bundled with this package, we need to run `manage.py makemigrations` to create the django-chroniker migrations, and then run `manage.py migrate to get them to work.

### PR DESCRIPTION
**Pull request by christianbundy**
Recent changes to `models.py` are making Django complain:

> Your models have changes that are not yet reflected in a migration, and so won't be applied.

This is the migration that's automatically created by `manage.py makemigrations`, which brings the database up-to-date with the models. It looks like ~8 of the changes were made to remove byte literals, and the others were trivial changes (like setting `Blank=True`).

Please let me know if you have any questions, thank you!

Resolves #58

### CODE REVIEW

**Comment by chrisspen** [comment]
I don't understand the need for this migration. A cursory glance at it shows it's the same as 0001_initial.py.

**Comment by chrisspen** [comment]
To clarify, I understand the error message you're trying to fix, but the fields the new migration alters aren't different than the fields created in the initial migration, so I'm unclear what change Django is detecting. Blank=True has no effect on schema. It only tells Django's admin validation to require a non-blank value.

**Comment by christianbundy** [comment]
It's possible that we have another problem causing #58, but it *seems* like the difference is in the byte literal (`b'foobar'` vs `'foobar`'). For example, here's `Job.frequency`, before and after:

``` python
# before
models.CharField(
    choices=[
        (b'YEARLY', 'Yearly'),
        (b'MONTHLY', 'Monthly'),
        (b'WEEKLY', 'Weekly'),
        (b'DAILY', 'Daily'),
        (b'HOURLY', 'Hourly'),
        (b'MINUTELY', 'Minutely'),
        (b'SECONDLY', 'Secondly')
    ],
    max_length=10,
    verbose_name='frequency'
)

# after
models.CharField(
    choices=[
        ('YEARLY', 'Yearly'),
        ('MONTHLY', 'Monthly'),
        ('WEEKLY', 'Weekly'),
        ('DAILY', 'Daily'),
        ('HOURLY', 'Hourly'),
        ('MINUTELY', 'Minutely'),
        ('SECONDLY', 'Secondly')
    ],
    max_length=10,
    verbose_name='frequency'
)
```

It looks like other projects have run into similar issues (e.g. divio/django-filer/issues/837), so it doesn't seem uncommon (although I don't know why they were added to the initial migration). I think I may have misspoke when I mentioned `Blank=True`, that may not have been a factor.

**Comment by christianbundy** [comment]
While documenting all of the changes I noticed that the hostname is actually being hardcoded to `charmion`, so I'll work on that real quick. Otherwise, here's an explanation of each change:

- [`Job.frequency`](https://github.com/christianbundy/django-chroniker/blob/a7045a649bdde65cd6f569ebe639307fbce62b3c/chroniker/migrations/0001_initial.py#L25): 7 byte literals
- [`Job.hostname`](https://github.com/christianbundy/django-chroniker/blob/a7045a649bdde65cd6f569ebe639307fbce62b3c/chroniker/migrations/0001_initial.py#L43): Hostname hardcoded to `charmion` (will fix)
- [`Job.maximum_log_entries`](https://github.com/christianbundy/django-chroniker/blob/a7045a649bdde65cd6f569ebe639307fbce62b3c/chroniker/migrations/0001_initial.py#L43): 1 byte literal
- [`Job.monitor_error_template`](https://github.com/christianbundy/django-chroniker/blob/a7045a649bdde65cd6f569ebe639307fbce62b3c/chroniker/migrations/0001_initial.py#L50): 
- [`JobDependency.dependee`](https://github.com/christianbundy/django-chroniker/blob/a7045a649bdde65cd6f569ebe639307fbce62b3c/chroniker/migrations/0001_initial.py#L69): 1 byte literal
- [`JobDependency.dependent`](https://github.com/christianbundy/django-chroniker/blob/a7045a649bdde65cd6f569ebe639307fbce62b3c/chroniker/migrations/0001_initial.py#L70): 1 byte literal
- [`JobDependency.wait_for_completion`](https://github.com/christianbundy/django-chroniker/blob/a7045a649bdde65cd6f569ebe639307fbce62b3c/chroniker/migrations/0001_initial.py#L66): 1 byte literal
- [`JobDependency.wait_for_next_run`](https://github.com/christianbundy/django-chroniker/blob/a7045a649bdde65cd6f569ebe639307fbce62b3c/chroniker/migrations/0001_initial.py#L68): 1 byte literal
- [`Log.duration_seconds`](https://github.com/christianbundy/django-chroniker/blob/a7045a649bdde65cd6f569ebe639307fbce62b3c/chroniker/migrations/0001_initial.py#L82): 1 byte literal

**Comment by chrisspen** [comment]
If it's just literals, and nothing that changes the schema, it would make more sense to fix 0001_initial.py than create a new migration.

**Comment by christianbundy** [comment]
The byte literals fixed in a7045a6 don't change the database schema, but modifying `0001_initial.py` doesn't resolve #58 now that it's already deployed in the wild. For example, if we modified `0001_initial.py` then when my existing deployments run `manage.py migrate` they wouldn't run the new version of `0001_initial.py`. Instead, they would continue to complain about models that haven't been reflected in a migration. If we don't create a new migration for this, #58 will persist for anyone using the current version of this package.

On the other hand, the `help_text` callable from 910ad639478d94c56f1d70cf6e3bd78c9dcbf159 *does* change the schema by using a dynamic hostname rather than having it hardcoded as "charmion". If we don't create a new migration for this, the incorrect hostname will persist for anyone using the current version of this package.

Please correct me if I'm misunderstanding anything here, and thanks for all your work on this package.

**Comment by chrisspen** [comment]
What version of Django are you using?

This looks related to a [bug](http://stackoverflow.com/questions/26503826/why-does-django-generate-migrations-for-help-text-and-verbose-name-changes) in some versions that create migrations for non-schema related changes.

**Comment by christianbundy** [comment]
I've reproduced this on both Django 1.8.13 and Django 1.9.7, but after some research I don't think it's a bug. It was brought up as Django ticket [#22837](https://code.djangoproject.com/ticket/22837) and was closed as "invalid". One of the core devs said [here](https://code.djangoproject.com/ticket/22837):

> This is by design. There are several reasons, not least of which for me that datamigrations at points in history need to have a full accurate representation of the models, including all their options not just those which affect the database.

**Comment by chrisspen** [comment]
Interesting and frustrating. Re-reading your earlier comment, I don't understand:

>On the other hand, the help_text callable from 910ad63 does change the schema by using a dynamic hostname rather than having it hardcoded as "charmion". If we don't create a new migration for this, the incorrect hostname will persist for anyone using the current version of this package.

How does the help text change schema? How does Django store help text in the database?

**Comment by chrisspen** [comment]
Could you list the exact steps you take to get the error message? I just created a blank Django 1.9.7 project, added Chroniker, and migrated it without error.

**Comment by christianbundy** [comment]
Sure, to make things easy I'm using [the official Django Docker image](https://hub.docker.com/_/django/). If you have Docker installed you can boot into the exact same environment with `docker run -it django bash`. Here's my console log:

``` console
root@fc63145df509:/# django-admin --version
1.9.6
root@fc63145df509:/# django-admin startproject example
root@fc63145df509:/# pip install django-chroniker
Collecting django-chroniker
  Downloading django-chroniker-0.8.5.tar.gz (89kB)
    100% |████████████████████████████████| 92kB 2.4MB/s 
Requirement already satisfied (use --upgrade to upgrade): Django>=1.5 in /usr/local/lib/python3.4/site-packages (from django-chroniker)
Collecting python-dateutil>=2.2 (from django-chroniker)
  Downloading python_dateutil-2.5.3-py2.py3-none-any.whl (201kB)
    100% |████████████████████████████████| 204kB 4.6MB/s 
Collecting psutil>=2.1.1 (from django-chroniker)
  Downloading psutil-4.2.0.tar.gz (311kB)
    100% |████████████████████████████████| 317kB 3.3MB/s 
Collecting six>=1.7.2 (from django-chroniker)
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six, python-dateutil, psutil, django-chroniker
  Running setup.py install for psutil ... done
  Running setup.py install for django-chroniker ... done
Successfully installed django-chroniker-0.8.5 psutil-4.2.0 python-dateutil-2.5.3 six-1.10.0
You are using pip version 8.1.1, however version 8.1.2 is available.
root@fc63145df509:/# echo "INSTALLED_APPS.append('django.contrib.sites')" >> example/example/settings.py
root@fc63145df509:/# echo "INSTALLED_APPS.append('chroniker')" >> example/example/settings.py
root@fc63145df509:/# example/manage.py migrate
/usr/local/lib/python3.4/site-packages/chroniker/admin.py:612: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a li
st of django.conf.urls.url() instances instead.
  self.admin_site.admin_view(self.view_full_stderr)),

/usr/local/lib/python3.4/site-packages/chroniker/admin.py:422: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a li
st of django.conf.urls.url() instances instead.
  name='chroniker_job_duration_graph'),

/usr/local/lib/python3.4/site-packages/chroniker/admin.py:758: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a li
st of django.conf.urls.url() instances instead.
  name="chroniker_job_run"),

Operations to perform:
  Apply all migrations: auth, sites, admin, contenttypes, sessions, chroniker
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying chroniker.0001_initial... OK
  Applying sessions.0001_initial... OK
  Applying sites.0001_initial... OK
  Applying sites.0002_alter_domain_unique... OK
root@fc63145df509:/# example/manage.py migrate
/usr/local/lib/python3.4/site-packages/chroniker/admin.py:612: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a li
st of django.conf.urls.url() instances instead.
  self.admin_site.admin_view(self.view_full_stderr)),

/usr/local/lib/python3.4/site-packages/chroniker/admin.py:422: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a li
st of django.conf.urls.url() instances instead.
  name='chroniker_job_duration_graph'),

/usr/local/lib/python3.4/site-packages/chroniker/admin.py:758: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a li
st of django.conf.urls.url() instances instead.
  name="chroniker_job_run"),

Operations to perform:
  Apply all migrations: admin, sessions, contenttypes, chroniker, auth, sites
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
root@fc63145df509:/# example/manage.py makemigrations
/usr/local/lib/python3.4/site-packages/chroniker/admin.py:758: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  name="chroniker_job_run"),

/usr/local/lib/python3.4/site-packages/chroniker/admin.py:422: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  name='chroniker_job_duration_graph'),

/usr/local/lib/python3.4/site-packages/chroniker/admin.py:612: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  self.admin_site.admin_view(self.view_full_stderr)),

Migrations for 'chroniker':
  0002_auto_20160523_1809.py:
    - Alter field frequency on job
    - Alter field hostname on job
    - Alter field maximum_log_entries on job
    - Alter field monitor_error_template on job
    - Alter field dependee on jobdependency
    - Alter field dependent on jobdependency
    - Alter field wait_for_completion on jobdependency
    - Alter field wait_for_next_run on jobdependency
    - Alter field wait_for_success on jobdependency
    - Alter field duration_seconds on log
```

Please let me know if I'm making any silly mistakes. It looks like `manage.py migrate` has to be run twice to trigger #58, which I'd *assume* is because the first one has some valid migrations to do. I'm not 100% sure though, maybe you know more about it?

In case I made a mistake somewhere, here's what I was attempting to do:

- Validate that we're using Django 1.9.6
- Scaffold an empty Django project
- Install the latest version of django-chroniker
- Add `django.contrib.sites` and `chroniker` to `INSTALLED_APPS` (I would've used a normal text editor for this, but doing it in the shell is easier to reproduce)
- Run the initial migrations
- Check for #58 

Thanks for you time on this, please let me know if there are any other steps you need me to take to reproduce.

**Comment by chrisspen** [comment]
Thanks for the detailed steps. Oddly, I'm still unable to reproduce the problem on Ubuntu 14.04. The only thing I did differently was instead of using Docker, I simply wrapped it all inside a virtualenv, but I don't see why that would act any differently as long as the package versions are the same.

Can you do me a favor and try running this instead?

    cd /tmp
    virtualenv test-env
    . ./test-env/bin/activate
    pip install Django
    django-admin.py startproject example
    pip install django-chroniker
    echo "INSTALLED_APPS.append('django.contrib.sites')" >> example/example/settings.py
    echo "INSTALLED_APPS.append('chroniker')" >> example/example/settings.py
    example/manage.py migrate
    example/manage.py migrate
    example/manage.py makemigrations

The output I get is:

    chris@charmion:~/git/django-chroniker$ cd /tmp
    chris@charmion:/tmp$ cd /tmp
    chris@charmion:/tmp$ virtualenv test-env
    New python executable in /tmp/test-env/bin/python
    Installing setuptools, pip, wheel...done.
    chris@charmion:/tmp$ . ./test-env/bin/activate
    (test-env) chris@charmion:/tmp$ pip install Django
    Collecting Django
      Using cached Django-1.9.6-py2.py3-none-any.whl
    Installing collected packages: Django
    Successfully installed Django-1.9.6
    (test-env) chris@charmion:/tmp$ django-admin.py startproject example
    (test-env) chris@charmion:/tmp$ pip install django-chroniker
    Collecting django-chroniker
    Collecting six>=1.7.2 (from django-chroniker)
      Using cached six-1.10.0-py2.py3-none-any.whl
    Requirement already satisfied (use --upgrade to upgrade): Django>=1.5 in ./test-env/lib/python2.7/site-packages (from django-chroniker)
    Collecting python-dateutil>=2.2 (from django-chroniker)
      Using cached python_dateutil-2.5.3-py2.py3-none-any.whl
    Collecting psutil>=2.1.1 (from django-chroniker)
    Installing collected packages: six, python-dateutil, psutil, django-chroniker
    Successfully installed django-chroniker-0.8.5 psutil-4.2.0 python-dateutil-2.5.3 six-1.10.0
    (test-env) chris@charmion:/tmp$ echo "INSTALLED_APPS.append('django.contrib.sites')" >> example/example/settings.py
    (test-env) chris@charmion:/tmp$ echo "INSTALLED_APPS.append('chroniker')" >> example/example/settings.py
    (test-env) chris@charmion:/tmp$ example/manage.py migrate
    /tmp/test-env/local/lib/python2.7/site-packages/chroniker/admin.py:612: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
      self.admin_site.admin_view(self.view_full_stderr)),

    /tmp/test-env/local/lib/python2.7/site-packages/chroniker/admin.py:422: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
      name='chroniker_job_duration_graph'),

    /tmp/test-env/local/lib/python2.7/site-packages/chroniker/admin.py:758: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
      name="chroniker_job_run"),

    Operations to perform:
      Apply all migrations: chroniker, sessions, admin, sites, auth, contenttypes
    Running migrations:
      Rendering model states... DONE
      Applying contenttypes.0001_initial... OK
      Applying auth.0001_initial... OK
      Applying admin.0001_initial... OK
      Applying admin.0002_logentry_remove_auto_add... OK
      Applying contenttypes.0002_remove_content_type_name... OK
      Applying auth.0002_alter_permission_name_max_length... OK
      Applying auth.0003_alter_user_email_max_length... OK
      Applying auth.0004_alter_user_username_opts... OK
      Applying auth.0005_alter_user_last_login_null... OK
      Applying auth.0006_require_contenttypes_0002... OK
      Applying auth.0007_alter_validators_add_error_messages... OK
      Applying chroniker.0001_initial... OK
      Applying sessions.0001_initial... OK
      Applying sites.0001_initial... OK
      Applying sites.0002_alter_domain_unique... OK
    (test-env) chris@charmion:/tmp$ example/manage.py migrate
    /tmp/test-env/local/lib/python2.7/site-packages/chroniker/admin.py:612: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
      self.admin_site.admin_view(self.view_full_stderr)),

    /tmp/test-env/local/lib/python2.7/site-packages/chroniker/admin.py:422: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
      name='chroniker_job_duration_graph'),

    /tmp/test-env/local/lib/python2.7/site-packages/chroniker/admin.py:758: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
      name="chroniker_job_run"),

    Operations to perform:
      Apply all migrations: chroniker, sessions, admin, sites, auth, contenttypes
    Running migrations:
      No migrations to apply.
    (test-env) chris@charmion:/tmp$ example/manage.py makemigrations
    /tmp/test-env/local/lib/python2.7/site-packages/chroniker/admin.py:422: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
      name='chroniker_job_duration_graph'),

    /tmp/test-env/local/lib/python2.7/site-packages/chroniker/admin.py:758: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
      name="chroniker_job_run"),

    /tmp/test-env/local/lib/python2.7/site-packages/chroniker/admin.py:612: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
      self.admin_site.admin_view(self.view_full_stderr)),

    No changes detected

**Comment by christianbundy** [comment]
Weird, I'm still encountering #58 within the virtualenv. There are only two differences I can see, but they seem like they make sense:

- **Python version**: in Python 2.7 `b'foo' == 'foo'`, but in Python 3.4 `b'foo' != b'foo'`. When the Python 2.7 interpreter compares the model to the initial migration it doesn't see a difference, but the Python 3.4 interpreter doesn't like it.
- **Hostname**: since your hostname is `charmion` that migration will never be triggered, but it creates a migration for everyone else.

Could those be the possible culprits? I've pasted my test below, maybe there's another factor.
 
``` console
root@fc63145df509:/example# pip install virtualenv
Collecting virtualenv
  Downloading virtualenv-15.0.1-py2.py3-none-any.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 767kB/s
Installing collected packages: virtualenv
Successfully installed virtualenv-15.0.1
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

root@fc63145df509:/example# cd /tmp

root@fc63145df509:/tmp# virtualenv test-env
Using base prefix '/usr/local'
New python executable in /tmp/test-env/bin/python3.4
Also creating executable in /tmp/test-env/bin/python
Installing setuptools, pip, wheel...done.

root@fc63145df509:/tmp# . ./test-env/bin/activate
(test-env)root@fc63145df509:/tmp# pip install Django
Collecting Django
  Using cached Django-1.9.6-py2.py3-none-any.whl
Installing collected packages: Django
Successfully installed Django-1.9.6

(test-env)root@fc63145df509:/tmp# django-admin.py startproject example

(test-env)root@fc63145df509:/tmp# pip install django-chroniker
Collecting django-chroniker
  Using cached django-chroniker-0.8.5.tar.gz
Requirement already satisfied (use --upgrade to upgrade): Django>=1.5 in ./test-env/lib/python3.4/site-packages (from django-chroniker)
Collecting python-dateutil>=2.2 (from django-chroniker)
  Using cached python_dateutil-2.5.3-py2.py3-none-any.whl
Collecting psutil>=2.1.1 (from django-chroniker)
  Using cached psutil-4.2.0.tar.gz
Collecting six>=1.7.2 (from django-chroniker)
  Using cached six-1.10.0-py2.py3-none-any.whl
Building wheels for collected packages: django-chroniker, psutil
  Running setup.py bdist_wheel for django-chroniker ... done
  Stored in directory: /root/.cache/pip/wheels/77/76/46/48cc405b719e7990a01535dd545e19979dc8f60b20451981e1
  Running setup.py bdist_wheel for psutil ... done
  Stored in directory: /root/.cache/pip/wheels/45/6b/34/070ff658d18f190a862d6b25b3011836a65c21bb3d4415b520
Successfully built django-chroniker psutil
Installing collected packages: six, python-dateutil, psutil, django-chroniker
Successfully installed django-chroniker-0.8.5 psutil-4.2.0 python-dateutil-2.5.3 six-1.10.0

(test-env)root@fc63145df509:/tmp# echo "INSTALLED_APPS.append('django.contrib.sites')" >> example/example/settings.py

(test-env)root@fc63145df509:/tmp# echo "INSTALLED_APPS.append('chroniker')" >> example/example/settings.py

(test-env)root@fc63145df509:/tmp# example/manage.py migrate
/tmp/test-env/lib/python3.4/site-packages/chroniker/admin.py:422: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  name='chroniker_job_duration_graph'),

/tmp/test-env/lib/python3.4/site-packages/chroniker/admin.py:612: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  self.admin_site.admin_view(self.view_full_stderr)),

/tmp/test-env/lib/python3.4/site-packages/chroniker/admin.py:758: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  name="chroniker_job_run"),

Operations to perform:
  Apply all migrations: sites, auth, chroniker, sessions, admin, contenttypes
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying chroniker.0001_initial... OK
  Applying sessions.0001_initial... OK
  Applying sites.0001_initial... OK
  Applying sites.0002_alter_domain_unique... OK

(test-env)root@fc63145df509:/tmp# example/manage.py migrate
/tmp/test-env/lib/python3.4/site-packages/chroniker/admin.py:422: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  name='chroniker_job_duration_graph'),

/tmp/test-env/lib/python3.4/site-packages/chroniker/admin.py:758: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  name="chroniker_job_run"),

/tmp/test-env/lib/python3.4/site-packages/chroniker/admin.py:612: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  self.admin_site.admin_view(self.view_full_stderr)),

Operations to perform:
  Apply all migrations: chroniker, contenttypes, admin, auth, sessions, sites
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

(test-env)root@fc63145df509:/tmp# example/manage.py makemigrations
/tmp/test-env/lib/python3.4/site-packages/chroniker/admin.py:758: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  name="chroniker_job_run"),

/tmp/test-env/lib/python3.4/site-packages/chroniker/admin.py:422: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  name='chroniker_job_duration_graph'),

/tmp/test-env/lib/python3.4/site-packages/chroniker/admin.py:612: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  self.admin_site.admin_view(self.view_full_stderr)),

Migrations for 'chroniker':
  0002_auto_20160523_1927.py:
    - Alter field frequency on job
    - Alter field hostname on job
    - Alter field maximum_log_entries on job
    - Alter field monitor_error_template on job
    - Alter field dependee on jobdependency
    - Alter field dependent on jobdependency
    - Alter field wait_for_completion on jobdependency
    - Alter field wait_for_next_run on jobdependency
    - Alter field wait_for_success on jobdependency
    - Alter field duration_seconds on log
```

**Comment by chrisspen** [comment]
Ah, I missed that you were using Python3. Yes, when I specify `-p python3` with virtualenv, now I reproduce the error.

**Comment by chrisspen** [comment]
If I try to apply the new migration you created, I get the error:

    NameError: name 'chroniker' is not defined

because you're referencing a model field without importing the model. Is that method documented? I haven't worked much with Django's new built-in migrations, but South always frowned on referencing hard-coded model fields in migrations.

**Comment by chrisspen** [comment]
When I run your new migration, I get the error:

    NameError: name 'chroniker' is not defined

because you reference a model field without importing the model. Adding `import chroniker` fixes that, but are you sure referencing a static method is appropriate in a migration? All the documentation I've seen frowns upon that sort of thing, since that'll break the migration if that method is ever removed or renamed.

**Comment by chrisspen** [comment]
Since there are no database changes involved here, the best way to fix this was to fix the initial migration. I had to make a few changes to make it backwards compatible with Py27, but I used your changes as a template for my [commit.](https://github.com/chrisspen/django-chroniker/commit/ad078711803012b39ef9164ea781f11372b1f2b1)

Thanks for pointing this out.

**Comment by christianbundy** [comment]
That looks great, thanks. I'll test it out ASAP on 0.8.6 (?) and let you know if there are any issues.

**Pull request closed without merging**
