### PR TITLE
#PSUTIL - AttributeErrors

### PR DESCRIPTION
**Pull request by diegofcoelho**
Fix of Attribute errors on several entries involving psutil.Process
function. https://pypi.python.org/pypi/psutil
Some functions were deprecated and cause chroniker to keep running
indefinitively.

### CODE REVIEW

**Comment by billyquith** [comment]
Yes, I'm getting the same problem. Either need to freeze `psutil` dependency at 2.1.1 or fix.

Wouldn't it be better to just increase the required version to 5.x in django-chronix `requirements.txt`, rather than test for older attributes and fallback?

**Comment by diegofcoelho** [comment]
@billyquith I agree that is a more definitive solution but I think it would be a more polite solution since it can be quite hard to track error back to psutil (I had to spend quite some time on it..).

However, I am not a professional programmer and have never helped fixing these things. Thus, I will follow @chrisspen lead and accept its decision.

Cheers

**Comment by chrisspen** [comment]
Please revert all whitespace changes. They're making it very difficult to read the diff.

**Comment by diegofcoelho** [comment]
Is it okay now? I am kinda lost, since I just leave PyCharm handle all the formatting..

**Comment by billyquith** [comment]
I simplified this change and updated the psutil version requirements: https://github.com/billyquith/django-chroniker/commit/25cdabfdd82b37b7f91ecd64756c3093e092f70d

**Comment by diegofcoelho** [comment]
@billyquith You didn't only simplified it but also removed compatibility to older versions of psutil.. I am okay with it anyway..

**Comment by chrisspen** [comment]
@diegofcoelho, Yes thanks. It looks good.

**Pull request merged**
