### PR TITLE
Master 1

### PR DESCRIPTION
**Pull request by helmetwearer**
Django 4.x compatibility 

Needed to add the migration for my purposes but that part of the pull request is probably not compatible with previous Django versions.

### CODE REVIEW

**Comment by Siburg** [comment]
Thank you. I would like to use this package with Django 4.2, so will also require this PR to be merged.

Two suggestions for it:
1. Eliminate the migration by adding an `AppConfig` that includes `default_auto_field = "django.db.models.AutoField"`.  (See https://docs.djangoproject.com/en/4.2/releases/3.2/#customizing-type-of-auto-created-primary-keys).
2. Reverse the code order in the try/except imports, so that they first try importing the current Django functions, and fall back on the deprecated/obsolete functions in the `except` clause.
3. Bonus points for amending the code to use the current Django function names, and importing the deprecated/obsolete names `as` current names.

**Comment by helmetwearer** [comment]
> Thank you @helmetwearer . I would like to use this package with Django 4.2, so will also require this PR to be merged.
> 
> Two (and a half) suggestions for it:
> 
> 1. Eliminate the migration by adding an `AppConfig` that includes `default_auto_field = "django.db.models.AutoField"`.  (See https://docs.djangoproject.com/en/4.2/releases/3.2/#customizing-type-of-auto-created-primary-keys).
> 2. Reverse the code order in the try/except imports, so that they first try importing the current Django functions, and fall back on the deprecated/obsolete functions in the `except` clause.
> 3. Bonus points for amending the code to use the current Django function names, and importing the deprecated/obsolete names `as` current names.

This seems way more correct and probably what it will take for this to get merged. I'm not sure I'll have the time to execute on it personally. We'll see.

**Comment by Siburg** [comment]
> I'm not sure I'll have the time to execute on it personally. We'll see.

I should have some time free this weekend. Would you like me to prepare a PR based on your work?

**Comment by helmetwearer** [comment]
If I haven't updated this PR by then, please feel free. In either case thanks for the review and implementation plan

**Comment by helmetwearer** [comment]
> > I'm not sure I'll have the time to execute on it personally. We'll see.
> 
> I should have some time free this weekend. Would you like me to prepare a PR based on your work?

You're a beast dude, nice job

**Pull request closed without merging**
