### PR TITLE
Added Django 2 compatibility 

### PR DESCRIPTION
**Pull request by RecNes**
Hello,

This is my first pull request. 
I added bunch of control code for Django 2 compatibility for failing imports.

I hope this pull request is applicable.

### CODE REVIEW

**Comment by RecNes** [comment]
I decied to remove this pull request due to django import problems

**Comment by chrisspen** [comment]
What import problems are you referring to? The unittests for your changes seemed to pass just fine. I'm only seeing some minor Pylint complaints

**Comment by RecNes** [comment]
the main problem is 'reverse' is moved from django.core.urlresolvers to django.urls

I just tried to add version check for django and try to Imports reverse from django.urls if version is greater than or equal to django 2

But Travis is giving errors on builds for many pythom/django combinations,  and I don't want to do mess in your project. So I canceled the request.

**Comment by chrisspen** [comment]
You shouldn't need to do any explicit version checking. Just use try/except statements to try one import path, and if it fails, try another. The Django core devs unfortunately love to arbitrarily move their stuff around, so I've had to do this a lot myself.

**Comment by RecNes** [comment]
If build fails are negligible, I'm going to do changes in github editor and open a pull request.
I have already forked and edited project files to make sure of use case is stricted for django 2 and python 3 only.

**Pull request closed without merging**
