### PR TITLE
Fixes for Django 1.8.x

### PR DESCRIPTION
**Pull request by nocarryr**
This removes South migrations and replaces them with those created by Django's new builtin migration system.

Also fixes an issue with the app registry not being initialized in the main chroniker script.

I've merged the most recent changes, but haven't yet tested those made in 5ce4ae867f7ae6ec88e3eef5ea794ef13643147d regarding atomic db transactions.

### CODE REVIEW

**Comment by chrisspen** [comment]
Thanks for the contribution, but I'm not sure this will work. This package will need to support Django<=1.7 for some time, and thus, South migrations, so I can't simply delete all the South migrations. I've read 1.8 and South migrations can live side by side, but need to be in separate folders. Is this your understand as well?

**Comment by nocarryr** [comment]
Yes, it seems as though they can on a per-app basis by using a settings.py variable:
https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-MIGRATION_MODULES

I can bring back in the South migrations and move the Django migrations into a separate folder.  Then add a version check in chroniker/settings.py to point to the correct locations.

Any suggestions for the new folder name?

**Comment by nocarryr** [comment]
@chrisspen I've implemented the changes from the above comments and tested to an extent, but not across all versions/platforms.

Let me know if there's anything you see that could be done differently.

**Comment by chrisspen** [comment]
Thanks, I appreciate the effort. I think this is close. I just pushed up some modifications to my test runner to separately test multiple Python+Django combinations, and everything's passing pre-merge. Could you please pull my commit and confirm your changes pass all those tests?

By default, it'll run everything with just:

    python setup.py test

If you find an error and want to retest a specific combination, you'd pass pv and dv arguments:

    python setup.py test --pv=2.7 --dv=1.7

**Comment by nocarryr** [comment]
Sounds good I'll merge and test in the morning

**Comment by nocarryr** [comment]
@chrisspen I found a few issues with module imports and added fixes in the most recent commits.

So far I've only been able to test with python-2.7 though.  Getting errors with the virtualenv creation steps in python3.

**Comment by nocarryr** [comment]
@chrisspen Sorry if you were waiting for a response about testing with py3.  I've been busy tracking down some db locking issues with long-running jobs.  (Probably a later topic)

Everything appears to be working in all pv's and dv's.

**Comment by chrisspen** [comment]
Sorry for the delay. Thanks for the contribution!

**Comment by nocarryr** [comment]
No worries.  Glad I could help

**Pull request merged**
